// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmb5p_mXbVi7RISqjQVHbe723R4lxtakU',
    appId: '1:338329851133:web:640c18260a41577553da94',
    messagingSenderId: '338329851133',
    projectId: 'chatapp-jp',
    authDomain: 'chatapp-jp.firebaseapp.com',
    storageBucket: 'chatapp-jp.appspot.com',
    measurementId: 'G-005RH5KX5L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHLnO-YjYZBJbDhTcPBZAW6ivjJi3R2So',
    appId: '1:338329851133:android:54637d45aec646af53da94',
    messagingSenderId: '338329851133',
    projectId: 'chatapp-jp',
    storageBucket: 'chatapp-jp.appspot.com',
  );
}
